name: Investment AI Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

# 警告に対応するための設定（環境変数をセット）
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # さらに最新の3.12に上げます
      - name: Install dependencies
        run: pip install -qU google-genai
      - name: Run analysis
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python main.py
